[package]
name = "zkurl"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your@email.com>"]
description = "zkURL type, parser, and utilities for Cubiq blockchain"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }