[package]
name = "networking"
version = "0.1.0"
edition = "2021"
authors = ["Arrnaya <arrnaya@email.com>"]
description = "Peer-to-peer networking for Cubiq blockchain"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
async-trait = "0.1"

# libp2p with necessary features enabled:
libp2p = { version = "0.51", features = [
    "gossipsub",
    "mdns",
    "identify",
    "tcp",
    "noise",
    "yamux",
    "websocket",
    "dns"
]}

log = "0.4"

[dev-dependencies]