[package]
name = "networking"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your@email.com>"]
description = "Peer-to-peer networking for Cubiq blockchain"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
# Add libp2p and other net deps as needed

[dev-dependencies]